name: CI

on:
  push:
    branches:
      - main
      - dev
    tags:        
      - v*

  workflow_dispatch:
  
jobs:
  dev-run:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world! Dev ${{ github.ref }} > one-line
        
  dev-get:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get one-line script
        run: cat one-line
          
  main-run:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world! Main ${{ github.ref }}
        
  release-run:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world! Release ${{ github.ref }}
